### ISSUE TITLE
retorno em formato de string

### ISSUE THREAD

**Issue by GustavoEmmel** [jovemnf/zenvia-api#1]
Estou recebendo o seguinte retorno da api:
Access denied for this resource

E o sdk tenta parsear o retorno (que é uma string e deveria ser um json) e quebra o codigo:

node_modules/zenvia-api/lib/send_sms.js:42
                return ok( JSON.parse(body));
                                ^
SyntaxError: Unexpected token A in JSON at position 0

**Comment by jovemnf** [comment]
Obrigado pela informação.. acertado..
